### ISSUE TITLE
[Improvement] Pavel, please make custom tails for the Worms faction. 

### ISSUE THREAD

**Issue by VladSuhanOFF** [PavelZinchenko/event-horizon-main#185] opened 2024-02-10 12:09 UTC
Custom tails are very necessary for bio-ships!

**Comment by PavelZinchenko** [comment] 2024-02-10 12:24
Guys, if you really want some feature, click 👍 or ❤️. I'll work on the most liked ones first.

**Comment by CrispyToken** [comment] 2024-02-10 12:31
Please correct me if I'm wrong, but is this not a duplicate of https://github.com/PavelZinchenko/event-horizon-main/issues/13 ?
If not, please clarify.

**Closed** 2024-02-10 13:57 UTC
